apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-00-02
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/localvols/user-00/wp-02"
    type: DirectoryOrCreate
