kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-claim-01
spec:
  storageClassName: user-00-persistent
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

